which:
  side: dev
conf:
  prop:
    client_host: 192.168.1.1
    customer-map:
      default1:
        age: 20
        name: df1
        surname: ls1
      test1:
        age: 25
        name: test1
        surname: ltest1
spring:
  profiles:
    active: dev
    default: live
  task:
    scheduling:
      pool:
        size: 4
  datasource:
    url: jdbc:h2:file:/data/demo
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
